# Generated by Django 5.1.15 on 2026-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('organization_or_name', models.CharField(max_length=200, verbose_name='organisation ou nom')),
                ('pole', models.CharField(blank=True, choices=[('DIAMNIADIO', 'Diamniadio'), ('LAC_ROSE', 'Lac Rose'), ('BOTH', 'Les deux pôles')], max_length=12)),
                ('representative', models.CharField(max_length=150, verbose_name='représentant')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('offers', models.TextField(blank=True)),
                ('needs', models.TextField(blank=True)),
                ('accept_charter', models.BooleanField(default=False, verbose_name='charte acceptée')),
                ('accept_privacy', models.BooleanField(default=False, verbose_name='confidentialité acceptée')),
            ],
            options={
                'verbose_name': "demande d'adhésion",
                'verbose_name_plural': "demandes d'adhésion",
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('amount_fcfa', models.PositiveIntegerField(verbose_name='cotisation (FCFA)')),
            ],
            options={
                'verbose_name': "catégorie d'adhésion",
                'verbose_name_plural': "catégories d'adhésion",
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
    ]
