# Generated by Django 5.1.15 on 2026-10-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.college'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='commissions',
            field=models.ManyToManyField(blank=True, related_name='+', to='organizations.commission'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.sector'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='memberships.membershipcategory'),
        ),
    ]
