# Generated by Django 5.1.15 on 2026-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('membership', 'Adhésion'), ('partnership', 'Partenariat'), ('events', 'Événements'), ('press', 'Presse'), ('volunteer', 'Bénévolat'), ('directory', 'Annuaire'), ('map', 'Cartographie'), ('other', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False, verbose_name='consentement')),
                ('email_sent', models.BooleanField(default=False, verbose_name='notification e-mail envoyée')),
                ('is_handled', models.BooleanField(db_index=True, default=False, verbose_name='traité')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
