# Generated by Django 5.1.15 on 2026-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Urban Hub Connect', max_length=120)),
                ('phone', models.CharField(default='+221 78 309 56 56', max_length=30)),
                ('whatsapp', models.CharField(default='221783095656', help_text='Format international sans +', max_length=30)),
                ('email', models.EmailField(default='infosurbanhubconnect@gmail.com', max_length=254)),
                ('address', models.CharField(default='SD City, Villa 115, Pôle urbain de Diamniadio', max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('footer_text', models.CharField(default="Association en cours de constitution · Initiative portée par M'ma Conciergerie", max_length=255)),
                ('legal_information', models.TextField(blank=True, help_text='[à compléter]', verbose_name='mentions légales')),
                ('privacy_policy', models.TextField(blank=True, help_text='[à compléter]', verbose_name='confidentialité')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
