# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('criteria', models.TextField(blank=True, help_text='[à compléter]', verbose_name='critères')),
            ],
            options={
                'verbose_name': "catégorie d'Awards",
                'verbose_name_plural': "catégories d'Awards",
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='public')),
                ('start_date', models.DateTimeField(verbose_name='début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('image', models.ImageField(blank=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size])),
                ('registration_url', models.URLField(blank=True, verbose_name="lien d'inscription")),
                ('is_featured', models.BooleanField(default=False, verbose_name='à la une')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "type d'événement",
                'verbose_name_plural': "types d'événement",
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'mission de bénévolat',
                'verbose_name_plural': 'missions de bénévolat',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='organisation ou personne')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('supporting_document', models.FileField(blank=True, upload_to='awards/', validators=[apps.core.validators.validate_pdf, apps.core.validators.validate_upload_size])),
                ('accept_privacy', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='events.awardcategory')),
            ],
            options={
                'verbose_name': 'candidature Awards',
                'verbose_name_plural': 'candidatures Awards',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessConnectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('participant_name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('what_offers', models.TextField(blank=True, verbose_name='ce que je propose')),
                ('what_needs', models.TextField(blank=True, verbose_name='ce que je recherche')),
                ('preferred_meetings', models.TextField(blank=True, verbose_name='rencontres souhaitées')),
                ('accept_privacy', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_connect_registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'inscription Business Connect',
                'verbose_name_plural': 'inscriptions Business Connect',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory', verbose_name='type'),
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(blank=True, max_length=255, verbose_name='disponibilités')),
                ('message', models.TextField(blank=True)),
                ('missions', models.ManyToManyField(blank=True, related_name='applications', to='events.volunteermission')),
            ],
            options={
                'verbose_name': 'candidature bénévole',
                'verbose_name_plural': 'candidatures bénévoles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
