# Generated by Django 5.1.15 on 2026-10-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('kind', models.CharField(choices=[('host_afterwork', 'Accueillir un After Work Connect'), ('book_visit', 'Réserver une visite (Portes Ouvertes)'), ('open_doors', 'Ouvrir les portes de son organisation'), ('caravan', "S'inscrire à la Caravane verte"), ('challenge', 'Défis Partenaires : proposer une solution')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('circuit', models.CharField(blank=True, choices=[('A', 'Circuit A « Cap sur le Lac Rose »'), ('B', 'Circuit B « Cap sur Diamniadio »')], max_length=1)),
                ('message', models.TextField(blank=True)),
                ('accept_waiver', models.BooleanField(default=False, verbose_name='décharge de responsabilité acceptée')),
                ('accept_privacy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'demande liée à un événement',
                'verbose_name_plural': 'demandes liées aux événements',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text="Avant cette date, le bouton d'inscription est grisé.", null=True, verbose_name='ouverture des inscriptions'),
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifiant technique : ne pas modifier pour les blocs existants.', max_length=60)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('body', models.TextField(blank=True, help_text='Paragraphes séparés par une ligne vide. Une ligne « heure | texte » devient une ligne de tableau.', verbose_name='texte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='publié')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.event')),
            ],
            options={
                'verbose_name': 'bloc de contenu',
                'verbose_name_plural': 'blocs de contenu',
                'ordering': ['order', 'id'],
                'unique_together': {('event', 'slug')},
            },
        ),
    ]
