# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('icon', models.CharField(blank=True, help_text='ex. landmark, graduation-cap', max_length=50, verbose_name='icône (nom Lucide)')),
            ],
            options={
                'verbose_name': 'catégorie de carte',
                'verbose_name_plural': 'catégories de carte',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('name', models.CharField(max_length=200, verbose_name='nom du lieu')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('submitter_name', models.CharField(max_length=150)),
                ('submitter_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'suggestion de lieu',
                'verbose_name_plural': 'suggestions de lieu',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('pole', models.CharField(blank=True, choices=[('DIAMNIADIO', 'Diamniadio'), ('LAC_ROSE', 'Lac Rose'), ('BOTH', 'Les deux pôles')], max_length=12, verbose_name='pôle')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='horaires')),
                ('image', models.ImageField(blank=True, upload_to='map/places/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='map.mapcategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'lieu de la carte',
                'verbose_name_plural': 'lieux de la carte',
                'ordering': ['name'],
            },
        ),
    ]
