# Generated by Django 5.1.15 on 2026-10-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplace',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_places', to='organizations.organization', verbose_name='organisation membre'),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='map.mapcategory'),
        ),
    ]
