# Generated by Django 5.1.15 on 2026-10-06 11:35

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesuggestion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail du lieu'),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='horaires'),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='téléphone du lieu'),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='photo',
            field=models.ImageField(blank=True, upload_to='map/suggestions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size]),
        ),
    ]
