# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('amount_fcfa', models.PositiveIntegerField(verbose_name='montant (FCFA)')),
                ('benefits', models.TextField(blank=True, help_text='[à compléter]', verbose_name='contreparties')),
            ],
            options={
                'verbose_name': 'formule de partenariat',
                'verbose_name_plural': 'formules de partenariat',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('company', models.CharField(max_length=200, verbose_name='entreprise / institution')),
                ('contact_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('accept_privacy', models.BooleanField(default=False)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='partnerships.partnershiptier')),
            ],
            options={
                'verbose_name': 'demande de partenariat',
                'verbose_name_plural': 'demandes de partenariat',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size])),
                ('website', models.URLField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmé (affiché publiquement)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('partnership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partnerships.partnershiptier')),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
