# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "catégorie d'article",
                'verbose_name_plural': "catégories d'article",
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('excerpt', models.TextField(blank=True, verbose_name='chapô')),
                ('content', models.TextField(blank=True, verbose_name='contenu')),
                ('featured_image', models.ImageField(blank=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size])),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='auteur')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.articlecategory')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
