# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('file', models.FileField(upload_to='documents/', validators=[apps.core.validators.validate_pdf, apps.core.validators.validate_upload_size])),
                ('category', models.CharField(choices=[('brochure', 'Plaquette'), ('partnership', 'Dossier de partenariat'), ('charter', 'Charte'), ('program', 'Programme'), ('awards_rules', 'Règlement Awards'), ('press_kit', 'Dossier de presse')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='téléchargeable publiquement')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
