# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('media', models.CharField(max_length=200, verbose_name='média')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('attendance_days', models.CharField(blank=True, max_length=200, verbose_name='jours de présence')),
            ],
            options={
                'verbose_name': 'accréditation presse',
                'verbose_name_plural': 'accréditations presse',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('document', models.FileField(blank=True, upload_to='press/', validators=[apps.core.validators.validate_pdf, apps.core.validators.validate_upload_size])),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
            ],
            options={
                'verbose_name': 'communiqué',
                'verbose_name_plural': 'communiqués',
                'ordering': ['-published_at'],
            },
        ),
    ]
