# Generated by Django 5.1.15 on 2026-10-02 13:47

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'collège',
                'verbose_name_plural': 'collèges',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='numéro')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'ordering': ['number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'secteur',
                'verbose_name_plural': 'secteurs',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publié')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validate_upload_size])),
                ('pole', models.CharField(choices=[('DIAMNIADIO', 'Diamniadio'), ('LAC_ROSE', 'Lac Rose'), ('BOTH', 'Les deux pôles')], max_length=12, verbose_name='pôle')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='quartier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True, verbose_name='présentation')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('member_founder', models.BooleanField(default=False, verbose_name='membre fondateur')),
                ('membership_status', models.CharField(choices=[('none', 'Non adhérent'), ('pending', 'Adhésion en cours'), ('active', 'Membre actif')], default='none', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name="téléphone de l'organisation")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name="email de l'organisation")),
                ('representative_name', models.CharField(blank=True, max_length=150, verbose_name='représentant')),
                ('representative_role', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('representative_phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone direct')),
                ('representative_email', models.EmailField(blank=True, max_length=254, verbose_name='email direct')),
                ('offers', models.TextField(blank=True, verbose_name="ce que l'organisation propose")),
                ('needs', models.TextField(blank=True, verbose_name="ce que l'organisation recherche")),
                ('validation_status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], db_index=True, default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.college', verbose_name='collège')),
                ('commissions', models.ManyToManyField(blank=True, related_name='organizations', to='organizations.commission')),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['name'],
            },
        ),
    ]
