# Generated by Django 5.1.15 on 2026-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(max_length=255, verbose_name='secteur'),
        ),
    ]
